# create_void_xs.py
# Run directly: python create_void_xs.py
# Generates a void material cross-section file for OpenSn,
# auto-populated with the LANL 70-group structure.

from pathlib import Path
import numpy as np

# ── Configuration ─────────────────────────────────────────────────────────────
# Path to the LANL 70g energy edges file, relative to THIS script's location.
# Adjust if your directory layout differs.
LANL70G_PATH = Path(__file__).parent / "../../../../code_files/mat_extract/LANL70g_eV.txt"

OUTPUT_FILENAME = "void.xs"


# ── Core writer ───────────────────────────────────────────────────────────────
def write_void_xs(num_groups: int, filename: str) -> None:
    """
    Write an OpenSn multigroup cross-section file for a void material.

    Parameters
    ----------
    num_groups : int
        Number of energy groups.
    filename : str
        Path of the output file to write.
    """
    if num_groups <= 0:
        raise ValueError("num_groups must be a positive integer.")

    num_moments = 1  # isotropic scattering only

    with open(filename, "w", encoding="utf-8") as f:
        f.write("# Void material cross section file generated by Python\n")
        f.write(f"NUM_GROUPS {num_groups}\n")
        f.write(f"NUM_MOMENTS {num_moments}\n\n")

        f.write("SIGMA_T_BEGIN\n")
        for g in range(num_groups):
            f.write(f"{g} 0.0\n")
        f.write("SIGMA_T_END\n\n\n")

        f.write("TRANSFER_MOMENTS_BEGIN\n")
        for g in range(num_groups):
            f.write(f"M_GFROM_GTO_VAL 0 {g} {g} 0.0\n")
        f.write("TRANSFER_MOMENTS_END\n")


# ── Auto-detect group count ───────────────────────────────────────────────────
def get_num_groups(lanl_path: Path, fallback: int = 70) -> int:
    """
    Derive num_groups from the LANL group-edge file (edges = groups + 1).
    Falls back to `fallback` if the file cannot be found or read.
    """
    resolved = lanl_path.resolve()
    if resolved.is_file():
        group_edges = np.loadtxt(str(resolved))
        ng = len(group_edges) - 1
        print(f"[INFO] Loaded group edges from: {resolved}")
        print(f"[INFO] Detected {ng} energy groups.")
        return ng
    else:
        print(f"[WARN] LANL70g file not found at: {resolved}")
        print(f"[WARN] Falling back to {fallback} groups.")
        return fallback


# ── Entry point ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    num_groups = get_num_groups(LANL70G_PATH, fallback=70)

    output_path = Path(__file__).parent / OUTPUT_FILENAME
    write_void_xs(num_groups, str(output_path))

    print(f"[DONE] Void XS file written to: {output_path.resolve()}")
    print(f"       Groups : {num_groups}")
    print(f"       SIGMA_T: all zeros")
    print(f"       Scatter: diagonal only, all zeros (isotropic, P0)")